name: tests

on: [workflow_call]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: "3.x"
    - name: Run unittests
      run: python3 -m unittest discover -s tests